### ISSUE TITLE
NameError: global name 'timout' is not defined

### ISSUE THREAD

**Issue by naterobbified** [nyxgeek/lyncsmash#5]
When i try to run this on the newest version of Kali or OS X I get the following error:

python lyncsmash.py enum -H lync.example.com -U usernames.txt -p Winter2017 -d EXAMPLE
[*] Getting timeout baseline
[*] Average timeout is: 3.9807
[*] Testing Credentials John.Doe:Winter2017
[*] Time for John.Doe: 3.865602
Traceback (most recent call last):
  File "lyncsmash.py", line 234, in <module>
    main()
  File "lyncsmash.py", line 68, in main
    timing_attack(args.host.rstrip(), args.usernames.rstrip(), args.passwd.rstrip(), args.domain.rstrip()) 
  File "lyncsmash.py", line 144, in timing_attack
    candidatevalue=float(float(response_time)/timeout)
NameError: global name 'timeout' is not defined

**Comment by nyxgeek** [comment]
Thanks! It was due to a restructuring of the timing attack into functions. All fixed now!
